using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace JiraClone.Api.Migrations;
public partial class AddIssueMetadata : Migration
{
 protected override void Up(MigrationBuilder migrationBuilder)
 {
  migrationBuilder.AddColumn<DateTime>(name: "DueDate", table: "Issues", type: "TEXT", nullable: true);
  migrationBuilder.CreateTable(name: "Labels", columns: table => new { Id = table.Column<int>(type: "INTEGER", nullable: false).Annotation("Sqlite:Autoincrement", true), ProjectId = table.Column<int>(type: "INTEGER", nullable: false), Name = table.Column<string>(type: "TEXT", nullable: false), Color = table.Column<string>(type: "TEXT", nullable: true) }, constraints: table => { table.PrimaryKey("PK_Labels", x => x.Id); table.ForeignKey("FK_Labels_Projects_ProjectId", x => x.ProjectId, "Projects", "Id", onDelete: ReferentialAction.Cascade); });
  migrationBuilder.CreateTable(name: "Components", columns: table => new { Id = table.Column<int>(type: "INTEGER", nullable: false).Annotation("Sqlite:Autoincrement", true), ProjectId = table.Column<int>(type: "INTEGER", nullable: false), Name = table.Column<string>(type: "TEXT", nullable: false), Description = table.Column<string>(type: "TEXT", nullable: true) }, constraints: table => { table.PrimaryKey("PK_Components", x => x.Id); table.ForeignKey("FK_Components_Projects_ProjectId", x => x.ProjectId, "Projects", "Id", onDelete: ReferentialAction.Cascade); });
  migrationBuilder.CreateTable(name: "IssueWatchers", columns: table => new { IssueId = table.Column<int>(type: "INTEGER", nullable: false), UserId = table.Column<int>(type: "INTEGER", nullable: false), CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false) }, constraints: table => { table.PrimaryKey("PK_IssueWatchers", x => new { x.IssueId, x.UserId }); table.ForeignKey("FK_IssueWatchers_Issues_IssueId", x => x.IssueId, "Issues", "Id", onDelete: ReferentialAction.Cascade); table.ForeignKey("FK_IssueWatchers_Users_UserId", x => x.UserId, "Users", "Id", onDelete: ReferentialAction.Restrict); });
  migrationBuilder.CreateTable(name: "IssueLabelLinks", columns: table => new { IssuesId = table.Column<int>(type: "INTEGER", nullable: false), LabelsId = table.Column<int>(type: "INTEGER", nullable: false) }, constraints: table => { table.PrimaryKey("PK_IssueLabelLinks", x => new { x.IssuesId, x.LabelsId }); table.ForeignKey("FK_IssueLabelLinks_Issues_IssuesId", x => x.IssuesId, "Issues", "Id", onDelete: ReferentialAction.Cascade); table.ForeignKey("FK_IssueLabelLinks_Labels_LabelsId", x => x.LabelsId, "Labels", "Id", onDelete: ReferentialAction.Cascade); });
  migrationBuilder.CreateTable(name: "IssueComponentLinks", columns: table => new { ComponentsId = table.Column<int>(type: "INTEGER", nullable: false), IssuesId = table.Column<int>(type: "INTEGER", nullable: false) }, constraints: table => { table.PrimaryKey("PK_IssueComponentLinks", x => new { x.ComponentsId, x.IssuesId }); table.ForeignKey("FK_IssueComponentLinks_Components_ComponentsId", x => x.ComponentsId, "Components", "Id", onDelete: ReferentialAction.Cascade); table.ForeignKey("FK_IssueComponentLinks_Issues_IssuesId", x => x.IssuesId, "Issues", "Id", onDelete: ReferentialAction.Cascade); });
  migrationBuilder.CreateIndex(name: "IX_Labels_ProjectId_Name", table: "Labels", columns: new[] { "ProjectId", "Name" }, unique: true); migrationBuilder.CreateIndex(name: "IX_Components_ProjectId_Name", table: "Components", columns: new[] { "ProjectId", "Name" }, unique: true); migrationBuilder.CreateIndex(name: "IX_IssueWatchers_UserId", table: "IssueWatchers", column: "UserId"); migrationBuilder.CreateIndex(name: "IX_IssueLabelLinks_LabelsId", table: "IssueLabelLinks", column: "LabelsId"); migrationBuilder.CreateIndex(name: "IX_IssueComponentLinks_IssuesId", table: "IssueComponentLinks", column: "IssuesId");
 }
 protected override void Down(MigrationBuilder migrationBuilder)
 {
  migrationBuilder.DropTable(name: "IssueComponentLinks"); migrationBuilder.DropTable(name: "IssueLabelLinks"); migrationBuilder.DropTable(name: "IssueWatchers"); migrationBuilder.DropTable(name: "Components"); migrationBuilder.DropTable(name: "Labels"); migrationBuilder.DropColumn(name: "DueDate", table: "Issues");
 }
}
