using JiraClone.Api.Data;
using JiraClone.Api.Models;
using JiraClone.Api.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JiraClone.Api.Controllers;

[ApiController, Route("api/[controller]")]
public sealed class IssuesController(JiraDbContext db, IssueApplicationService service, ProjectAuthorizationService authorization) : ControllerBase
{
    [HttpGet]
    public async Task<IActionResult> Get([FromQuery] int? projectId, [FromQuery] int? sprintId, [FromQuery] int? assigneeId, [FromQuery] IssueStatus? status, [FromQuery] IssuePriority? priority, [FromQuery] IssueType? type, [FromQuery] string? search, CancellationToken ct)
    {
        if (projectId is not null) await authorization.EnsureCanViewAsync(projectId.Value, ct); else { var ids = await authorization.GetVisibleProjectIdsAsync(ct); var queryAll = db.Issues.AsNoTracking().Where(x => ids.Contains(x.ProjectId)); return Ok(await Filter(queryAll, sprintId, assigneeId, status, priority, type, search).Select(x => new IssueResponse(x.Id, x.Project.Key + "-" + x.Number, x.Title, x.Description, x.Status.ToString(), x.Priority.ToString(), x.Type.ToString(), x.StoryPoints, x.SprintId, x.Assignee == null ? null : new UserSummary(x.Assignee.Id, x.Assignee.Name, x.Assignee.Avatar), x.UpdatedAt)).ToListAsync(ct)); }
        var query = db.Issues.AsNoTracking().Where(x => x.ProjectId == projectId); return Ok(await Filter(query, sprintId, assigneeId, status, priority, type, search).Select(x => new IssueResponse(x.Id, x.Project.Key + "-" + x.Number, x.Title, x.Description, x.Status.ToString(), x.Priority.ToString(), x.Type.ToString(), x.StoryPoints, x.SprintId, x.Assignee == null ? null : new UserSummary(x.Assignee.Id, x.Assignee.Name, x.Assignee.Avatar), x.UpdatedAt)).ToListAsync(ct));
    }

    [HttpGet("{id:int}")]
    public async Task<IActionResult> GetById(int id, CancellationToken ct)
    {
        var issue = await db.Issues.AsNoTracking().Include(x => x.Project).Include(x => x.Assignee).Include(x => x.Labels).Include(x => x.Components).Include(x => x.Watchers).ThenInclude(x => x.User).Include(x => x.Comments).ThenInclude(x => x.Author).Include(x => x.Activities).ThenInclude(x => x.Actor).FirstOrDefaultAsync(x => x.Id == id, ct);
        if (issue is null) return NotFound(); await authorization.EnsureCanViewAsync(issue.ProjectId, ct);
        return Ok(new IssueDetailsResponse(issue.Id, issue.Project.Key + "-" + issue.Number, issue.Title, issue.Description, issue.Status.ToString(), issue.Priority.ToString(), issue.Type.ToString(), issue.StoryPoints, issue.DueDate, issue.SprintId, issue.Assignee == null ? null : new UserSummary(issue.Assignee.Id, issue.Assignee.Name, issue.Assignee.Avatar), issue.UpdatedAt, issue.Labels.Select(x => new LabelResponse(x.Id, x.Name, x.Color)).OrderBy(x => x.Name).ToList(), issue.Components.Select(x => new ComponentResponse(x.Id, x.Name, x.Description)).OrderBy(x => x.Name).ToList(), issue.Watchers.Select(x => new WatcherResponse(x.User.Id, x.User.Name, x.User.Avatar)).OrderBy(x => x.Name).ToList(), issue.Comments.OrderBy(x => x.CreatedAt).Select(x => new CommentResponse(x.Id, x.Body, x.Author.Name, x.Author.Avatar, x.CreatedAt)).ToList(), issue.Activities.OrderByDescending(x => x.CreatedAt).Select(x => new ActivityResponse(x.Id, x.Type.ToString(), x.OldValue, x.NewValue, x.Actor.Name, x.Actor.Avatar, x.CreatedAt)).ToList()));
    }

    [HttpPost] public async Task<IActionResult> Create(CreateIssueRequest request, CancellationToken ct) { await authorization.EnsureCanEditAsync(request.ProjectId, ct); var issue = await service.CreateAsync(new CreateIssueCommand(request.ProjectId, request.Title, request.Description, request.Status, request.Priority, request.Type, request.AssigneeId, request.SprintId, request.StoryPoints), ct); return Created($"/api/issues/{issue.Id}", issue.Id); }
    [HttpPut("{id:int}")] public async Task<IActionResult> Update(int id, UpdateIssueRequest request, CancellationToken ct) { var projectId = await db.Issues.Where(x => x.Id == id).Select(x => (int?)x.ProjectId).FirstOrDefaultAsync(ct); if (projectId is null) return NotFound(); await authorization.EnsureCanEditAsync(projectId.Value, ct); await service.UpdateAsync(id, new UpdateIssueCommand(request.Title, request.Description, request.Priority, request.Type, request.StoryPoints, request.AssigneeId, request.SprintId), ct); return NoContent(); }
    [HttpPatch("{id:int}/status")] public async Task<IActionResult> UpdateStatus(int id, UpdateStatusRequest request, CancellationToken ct) { var projectId = await db.Issues.Where(x => x.Id == id).Select(x => (int?)x.ProjectId).FirstOrDefaultAsync(ct); if (projectId is null) return NotFound(); await authorization.EnsureCanEditAsync(projectId.Value, ct); await service.MoveAsync(id, request.Status, ct); return NoContent(); }
    [HttpPost("{id:int}/comments")] public async Task<IActionResult> AddComment(int id, CreateCommentRequest request, CancellationToken ct) { if (string.IsNullOrWhiteSpace(request.Body)) return BadRequest(new { message = "Comment body is required." }); var projectId = await db.Issues.Where(x => x.Id == id).Select(x => (int?)x.ProjectId).FirstOrDefaultAsync(ct); if (projectId is null) return NotFound(); await authorization.EnsureCanEditAsync(projectId.Value, ct); var userId = authorization.GetCurrentUserId(); if (userId is null) return Unauthorized(); var now = DateTime.UtcNow; var comment = new IssueComment { IssueId = id, AuthorId = userId.Value, Body = request.Body.Trim(), CreatedAt = now }; db.IssueComments.Add(comment); db.IssueActivities.Add(new IssueActivity { IssueId = id, ActorId = userId.Value, Type = IssueActivityType.CommentAdded, NewValue = "Comment added", CreatedAt = now }); await db.SaveChangesAsync(ct); return Created($"/api/issues/{id}", comment.Id); }
    private IQueryable<Issue> Filter(IQueryable<Issue> query, int? sprintId, int? assigneeId, IssueStatus? status, IssuePriority? priority, IssueType? type, string? search) { query = query.Include(x => x.Assignee).Include(x => x.Project); if (sprintId is not null) query = query.Where(x => x.SprintId == sprintId); if (assigneeId is not null) query = query.Where(x => x.AssigneeId == assigneeId); if (status is not null) query = query.Where(x => x.Status == status); if (priority is not null) query = query.Where(x => x.Priority == priority); if (type is not null) query = query.Where(x => x.Type == type); if (!string.IsNullOrWhiteSpace(search)) query = query.Where(x => x.Title.Contains(search) || x.Description.Contains(search) || (x.Project.Key + "-" + x.Number).Contains(search)); return query.OrderByDescending(x => x.UpdatedAt); }
}
public sealed record IssueResponse(int Id, string Key, string Title, string Description, string Status, string Priority, string Type, int StoryPoints, int? SprintId, UserSummary? Assignee, DateTime UpdatedAt);
public sealed record IssueDetailsResponse(int Id, string Key, string Title, string Description, string Status, string Priority, string Type, int StoryPoints, DateTime? DueDate, int? SprintId, UserSummary? Assignee, DateTime UpdatedAt, IReadOnlyList<LabelResponse> Labels, IReadOnlyList<ComponentResponse> Components, IReadOnlyList<WatcherResponse> Watchers, IReadOnlyList<CommentResponse> Comments, IReadOnlyList<ActivityResponse> Activities);
public sealed record UserSummary(int Id, string Name, string Avatar); public sealed record WatcherResponse(int Id, string Name, string Avatar); public sealed record CommentResponse(int Id, string Body, string Author, string Avatar, DateTime CreatedAt); public sealed record ActivityResponse(int Id, string Type, string? OldValue, string? NewValue, string Actor, string Avatar, DateTime CreatedAt);
public sealed record CreateIssueRequest(int ProjectId, string Title, string? Description, IssueStatus Status = IssueStatus.Todo, IssuePriority Priority = IssuePriority.Medium, IssueType Type = IssueType.Task, int? AssigneeId = null, int? SprintId = null, int StoryPoints = 0); public sealed record UpdateIssueRequest(string Title, string? Description, IssuePriority Priority, IssueType Type, int StoryPoints, int? AssigneeId, int? SprintId); public sealed record UpdateStatusRequest(IssueStatus Status); public sealed record CreateCommentRequest(string Body);
