import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { JiraApiService, IssueDetails, IssuePriority, IssueStatus, IssueType, Label, Component as IssueComponent } from '../../core/jira-api.service';
import { PermissionService } from '../../core/permission.service';

@Component({ selector: 'app-issue-detail', standalone: true, imports: [CommonModule, FormsModule, RouterLink], template: `
<div class="p-4 lg:p-8 max-w-7xl mx-auto" *ngIf="issue() as i">
  <div class="breadcrumbs text-sm mb-3"><ul><li><a routerLink="/board">Board</a></li><li>{{i.key}}</li></ul></div>
  <div class="flex flex-col lg:flex-row gap-6">
    <main class="flex-1 space-y-5">
      <section class="card bg-base-100 border border-base-300 shadow-sm"><div class="card-body">
        <div class="flex items-start justify-between gap-4"><div class="w-full"><div class="badge badge-outline mb-3">{{i.key}}</div><input class="input input-ghost text-2xl font-bold w-full px-0" [(ngModel)]="title" [disabled]="!permissions.canEdit()" aria-label="Issue title"></div><span class="badge" [class.badge-success]="i.status==='Done'">{{i.status}}</span></div>
        <textarea class="textarea textarea-bordered w-full min-h-40 mt-4" [(ngModel)]="description" [disabled]="!permissions.canEdit()" aria-label="Issue description"></textarea>
        <div class="flex justify-end mt-3"><button class="btn btn-primary" (click)="save()" [disabled]="saving() || !permissions.canEdit() || !title.trim()">{{saving()?'Saving…':'Save changes'}}</button></div>
      </div></section>
      <section class="card bg-base-100 border border-base-300 shadow-sm"><div class="card-body"><div class="flex items-center justify-between"><h2 class="card-title">Labels</h2><span class="badge badge-ghost">{{i.labels.length}}</span></div><div class="flex flex-wrap gap-2 mt-3"><span *ngFor="let l of i.labels" class="badge badge-lg gap-2"><span>{{l.name}}</span><button *ngIf="permissions.canEdit()" class="btn btn-ghost btn-xs" (click)="removeLabel(l)" aria-label="Remove label">×</button></span><span *ngIf="!i.labels.length" class="text-sm text-base-content/50">No labels.</span></div><div *ngIf="permissions.canEdit()" class="join mt-4"><select class="select select-bordered join-item" [(ngModel)]="selectedLabelId"><option [ngValue]="null">Add label…</option><option *ngFor="let l of labels()" [ngValue]="l.id" [disabled]="hasLabel(i,l.id)">{{l.name}}</option></select><button class="btn btn-outline join-item" (click)="addLabel()" [disabled]="!selectedLabelId">Add</button></div></div></section>
      <section class="card bg-base-100 border border-base-300 shadow-sm"><div class="card-body"><div class="flex items-center justify-between"><h2 class="card-title">Components</h2><span class="badge badge-ghost">{{i.components.length}}</span></div><div class="flex flex-wrap gap-2 mt-3"><span *ngFor="let c of i.components" class="badge badge-outline badge-lg gap-2">{{c.name}}<button *ngIf="permissions.canEdit()" class="btn btn-ghost btn-xs" (click)="removeComponent(c)" aria-label="Remove component">×</button></span><span *ngIf="!i.components.length" class="text-sm text-base-content/50">No components.</span></div><div *ngIf="permissions.canEdit()" class="join mt-4"><select class="select select-bordered join-item" [(ngModel)]="selectedComponentId"><option [ngValue]="null">Add component…</option><option *ngFor="let c of components()" [ngValue]="c.id" [disabled]="hasComponent(i,c.id)">{{c.name}}</option></select><button class="btn btn-outline join-item" (click)="addComponent()" [disabled]="!selectedComponentId">Add</button></div></div></section>
      <section class="card bg-base-100 border border-base-300 shadow-sm"><div class="card-body"><div class="flex items-center justify-between"><h2 class="card-title">Watchers</h2><button *ngIf="permissions.canEdit()" class="btn btn-sm btn-outline" (click)="watchSelf()">Watch</button></div><div class="flex flex-wrap gap-2 mt-3"><span *ngFor="let w of i.watchers" class="badge badge-lg gap-2">{{w.name}}<button *ngIf="permissions.canEdit()" class="btn btn-ghost btn-xs" (click)="removeWatcher(w.id)" aria-label="Remove watcher">×</button></span><span *ngIf="!i.watchers.length" class="text-sm text-base-content/50">No watchers.</span></div></div></section>
      <section class="card bg-base-100 border border-base-300 shadow-sm"><div class="card-body"><h2 class="card-title">Comments</h2><textarea class="textarea textarea-bordered w-full mt-3" [(ngModel)]="commentText" placeholder="Add a comment…" [disabled]="!permissions.canEdit()"></textarea><div class="flex justify-end mt-2"><button class="btn btn-sm btn-outline" (click)="addComment()" [disabled]="!commentText.trim() || !permissions.canEdit()">Comment</button></div><div class="divider"></div><div *ngFor="let c of i.comments" class="flex gap-3 py-3"><div class="avatar placeholder"><div class="bg-base-300 rounded-full w-9"><span>{{c.author.charAt(0)}}</span></div></div><div><div class="font-semibold">{{c.author}} <span class="text-xs font-normal text-base-content/50">{{c.createdAt | date:'dd MMM yyyy, HH:mm'}}</span></div><p class="whitespace-pre-wrap mt-1">{{c.body}}</p></div></div><p *ngIf="!i.comments.length" class="text-sm text-base-content/50">No comments yet.</p></div></section>
      <section class="card bg-base-100 border border-base-300 shadow-sm"><div class="card-body"><h2 class="card-title">Activity</h2><ul class="timeline timeline-vertical mt-3"><li *ngFor="let a of i.activities"><div class="timeline-start text-xs text-base-content/50">{{a.createdAt | date:'dd MMM, HH:mm'}}</div><div class="timeline-middle">•</div><div class="timeline-end pb-5"><strong>{{a.actor}}</strong> {{a.type}} <span *ngIf="a.oldValue">from <b>{{a.oldValue}}</b></span><span *ngIf="a.newValue">to <b>{{a.newValue}}</b></span></div></li></ul><p *ngIf="!i.activities.length" class="text-sm text-base-content/50">No activity recorded.</p></div></section>
    </main>
    <aside class="w-full lg:w-80 space-y-5"><section class="card bg-base-100 border border-base-300 shadow-sm"><div class="card-body"><h2 class="card-title text-base">Details</h2><label class="form-control"><span class="label-text">Status</span><select class="select select-bordered" [ngModel]="i.status" (ngModelChange)="changeStatus($event)" [disabled]="!permissions.canEdit()"><option *ngFor="let s of statuses" [ngValue]="s">{{s}}</option></select></label><label class="form-control mt-3"><span class="label-text">Priority</span><select class="select select-bordered" [(ngModel)]="priority" [disabled]="!permissions.canEdit()"><option *ngFor="let p of priorities">{{p}}</option></select></label><label class="form-control mt-3"><span class="label-text">Type</span><select class="select select-bordered" [(ngModel)]="type" [disabled]="!permissions.canEdit()"><option *ngFor="let t of types">{{t}}</option></select></label><label class="form-control mt-3"><span class="label-text">Story points</span><input type="number" min="0" class="input input-bordered" [(ngModel)]="storyPoints" [disabled]="!permissions.canEdit()"></label><label class="form-control mt-3"><span class="label-text">Due date</span><input type="date" class="input input-bordered" [ngModel]="dueDate" (ngModelChange)="dueDate=$event" [disabled]="!permissions.canEdit()"><button *ngIf="permissions.canEdit()" class="btn btn-sm btn-outline mt-2" (click)="saveDueDate()">Save due date</button></label></div></section></aside>
  </div>
</div><div *ngIf="loading()" class="flex justify-center p-20"><span class="loading loading-spinner loading-lg"></span></div><div *ngIf="error()" class="alert alert-error m-4">{{error()}}</div>` })
export class IssueDetailComponent implements OnInit {
  private readonly api=inject(JiraApiService); private readonly route=inject(ActivatedRoute); readonly permissions=inject(PermissionService); readonly issue=signal<IssueDetails|null>(null); readonly loading=signal(true); readonly saving=signal(false); readonly error=signal<string|null>(null); readonly labels=signal<Label[]>([]); readonly components=signal<IssueComponent[]>([]);
  title=''; description=''; priority:IssuePriority='Medium'; type:IssueType='Task'; storyPoints=0; commentText=''; dueDate=''; selectedLabelId:number|null=null; selectedComponentId:number|null=null; id=0;
  readonly statuses:IssueStatus[]=['Backlog','Todo','InProgress','InReview','Done']; readonly priorities:IssuePriority[]=['Lowest','Low','Medium','High','Highest']; readonly types:IssueType[]=['Story','Task','Bug','Epic'];
  ngOnInit():void{this.id=Number(this.route.snapshot.paramMap.get('id'));this.load();}
  load():void{this.loading.set(true);this.api.issue(this.id).subscribe({next:i=>{this.issue.set(i);this.title=i.title;this.description=i.description;this.priority=i.priority;this.type=i.type;this.storyPoints=i.storyPoints;this.dueDate=i.dueDate?.slice(0,10)??'';this.api.projectMembers(i.projectId).subscribe({next:members=>{const userId=this.permissions.currentUserId();this.permissions.setProjectRole(members.find(x=>x.userId===userId)?.role);}});this.api.labels(i.projectId).subscribe({next:x=>this.labels.set(x)});this.api.components(i.projectId).subscribe({next:x=>this.components.set(x)});},error:()=>this.error.set('Unable to load issue.'),complete:()=>this.loading.set(false)});}
  save():void{const i=this.issue();if(!i||!this.permissions.canEdit())return;this.saving.set(true);this.api.update(i.id,{title:this.title.trim(),description:this.description,priority:this.priority,type:this.type,storyPoints:Math.max(0,Number(this.storyPoints)),assigneeId:i.assignee?.id,sprintId:i.sprintId}).subscribe({next:()=>this.load(),error:()=>this.error.set('Unable to save issue.'),complete:()=>this.saving.set(false)});}
  changeStatus(status:IssueStatus):void{if(!this.permissions.canEdit()||status===this.issue()?.status)return;this.api.move(this.id,status).subscribe({next:()=>this.load(),error:()=>this.error.set('Unable to transition issue.')});}
  addComment():void{const body=this.commentText.trim();if(!body||!this.permissions.canEdit())return;this.api.comment(this.id,body).subscribe({next:()=>{this.commentText='';this.load();},error:()=>this.error.set('Unable to add comment.')});}
  hasLabel(i:IssueDetails,id:number):boolean{return i.labels.some(x=>x.id===id);} hasComponent(i:IssueDetails,id:number):boolean{return i.components.some(x=>x.id===id);}
  addLabel():void{if(this.selectedLabelId==null)return;this.api.addLabel(this.id,this.selectedLabelId).subscribe({next:()=>{this.selectedLabelId=null;this.load()},error:()=>this.error.set('Unable to add label.')});} removeLabel(l:Label):void{this.api.removeLabel(this.id,l.id).subscribe({next:()=>this.load(),error:()=>this.error.set('Unable to remove label.')});}
  addComponent():void{if(this.selectedComponentId==null)return;this.api.addComponent(this.id,this.selectedComponentId).subscribe({next:()=>{this.selectedComponentId=null;this.load()},error:()=>this.error.set('Unable to add component.')});} removeComponent(c:IssueComponent):void{this.api.removeComponent(this.id,c.id).subscribe({next:()=>this.load(),error:()=>this.error.set('Unable to remove component.')});}
  watchSelf():void{const id=this.permissions.currentUserId();if(id==null)return;this.api.addWatcher(this.id,id).subscribe({next:()=>this.load(),error:()=>this.error.set('Unable to add watcher.')});} removeWatcher(id:number):void{this.api.removeWatcher(this.id,id).subscribe({next:()=>this.load(),error:()=>this.error.set('Unable to remove watcher.')});}
  saveDueDate():void{this.api.setDueDate(this.id,this.dueDate?this.dueDate:null).subscribe({next:()=>this.load(),error:()=>this.error.set('Unable to update due date.')});}
}
