import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { JiraApiService, Project, ProjectDashboard } from '../../core/jira-api.service';

@Component({ selector: 'app-project-dashboard', standalone: true, imports: [CommonModule, FormsModule], template: `
<div class="p-4 lg:p-8 max-w-[1600px] mx-auto"><div class="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-7"><div><div class="breadcrumbs text-sm"><ul><li>Project</li><li>Dashboard</li></ul></div><h1 class="text-3xl font-bold mt-2">Project dashboard</h1><p class="text-base-content/60">Delivery health, active sprint and recent velocity.</p></div><select class="select select-bordered bg-base-100" [(ngModel)]="projectId" (change)="load()"><option *ngFor="let p of projects()" [ngValue]="p.id">{{p.key}} — {{p.name}}</option></select></div>
<div *ngIf="error()" class="alert alert-error mb-5">{{error()}}</div><div *ngIf="loading()" class="flex justify-center p-20"><span class="loading loading-spinner loading-lg"></span></div>
<ng-container *ngIf="data() as d"><div class="grid grid-cols-2 xl:grid-cols-5 gap-3"><div class="stat bg-base-100 border border-base-300 rounded-box shadow-sm"><div class="stat-title">Total issues</div><div class="stat-value text-2xl">{{d.totalIssues}}</div></div><div class="stat bg-base-100 border border-base-300 rounded-box shadow-sm"><div class="stat-title">Open</div><div class="stat-value text-2xl">{{d.openIssues}}</div></div><div class="stat bg-base-100 border border-base-300 rounded-box shadow-sm"><div class="stat-title">Completed</div><div class="stat-value text-2xl">{{d.completedIssues}}</div></div><div class="stat bg-base-100 border border-base-300 rounded-box shadow-sm"><div class="stat-title">Story points</div><div class="stat-value text-2xl">{{d.totalStoryPoints}}</div></div><div class="stat bg-base-100 border border-base-300 rounded-box shadow-sm"><div class="stat-title">Delivered</div><div class="stat-value text-2xl">{{d.completedStoryPoints}}</div></div></div>
<div class="grid grid-cols-1 xl:grid-cols-3 gap-5 mt-5"><section class="card bg-base-100 border border-base-300 shadow-sm xl:col-span-2"><div class="card-body"><h2 class="card-title">Work distribution</h2><div class="space-y-4 mt-4"><div *ngFor="let s of d.statusDistribution"><div class="flex justify-between text-sm mb-1"><span>{{s.status}}</span><span>{{s.issues}} issues · {{s.storyPoints}} pts</span></div><progress class="progress progress-primary w-full" [value]="s.issues" [max]="d.totalIssues || 1"></progress></div></div></div></section>
<section class="card bg-base-100 border border-base-300 shadow-sm"><div class="card-body"><h2 class="card-title">Active sprint</h2><ng-container *ngIf="d.activeSprint as s; else noSprint"><h3 class="font-bold text-lg mt-3">{{s.name}}</h3><p class="text-sm text-base-content/60">{{s.startDate | date:'dd MMM'}} — {{s.endDate | date:'dd MMM yyyy'}}</p><div class="stats stats-vertical bg-base-200 mt-4"><div class="stat p-3"><div class="stat-title">Issues</div><div class="stat-value text-xl">{{s.issueCount}}</div></div><div class="stat p-3"><div class="stat-title">Progress</div><div class="stat-value text-xl">{{percent(s.completedPoints,s.committedPoints)}}%</div></div></div><progress class="progress progress-success w-full mt-4" [value]="s.completedPoints" [max]="s.committedPoints || 1"></progress></ng-container><ng-template #noSprint><p class="text-base-content/50 mt-4">No active sprint.</p></ng-template></div></section></div>
<section class="card bg-base-100 border border-base-300 shadow-sm mt-5"><div class="card-body"><div class="flex justify-between items-center"><div><h2 class="card-title">Velocity</h2><p class="text-sm text-base-content/60">Completed story points per sprint.</p></div><span class="badge badge-outline">Last {{d.velocity.length}} sprints</span></div><div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4 items-end mt-8 min-h-56"><div *ngFor="let v of d.velocity" class="flex flex-col justify-end h-48"><div class="text-center text-sm font-semibold mb-2">{{v.completedPoints}}</div><div class="bg-primary rounded-t-box min-h-1" [style.height.px]="barHeight(v.completedPoints,d.velocity)"></div><div class="text-center text-xs text-base-content/60 mt-2 truncate" [title]="v.sprintName">{{v.sprintName}}</div></div><div *ngIf="!d.velocity.length" class="col-span-full text-center text-base-content/40">Complete a sprint to start tracking velocity.</div></div></div></section></ng-container></div>` })
export class ProjectDashboardComponent implements OnInit {
  private readonly api=inject(JiraApiService); readonly projects=signal<Project[]>([]); readonly data=signal<ProjectDashboard|null>(null); readonly loading=signal(false); readonly error=signal<string|null>(null); projectId=0;
  ngOnInit():void{this.api.projects().subscribe({next:p=>{this.projects.set(p);if(p.length){this.projectId=p[0].id;this.load();}}});}
  load():void{if(!this.projectId)return;this.loading.set(true);this.error.set(null);this.api.dashboard(this.projectId).subscribe({next:x=>this.data.set(x),error:()=>this.error.set('Unable to load project dashboard.'),complete:()=>this.loading.set(false)});}
  percent(done:number,total:number):number{return total?Math.round(done*100/total):0;}
  barHeight(value:number,items:{completedPoints:number}[]):number{const max=Math.max(1,...items.map(x=>x.completedPoints));return Math.max(4,Math.round(value/max*150));}
}
